### ISSUE TITLE
TypeError in 1.5.4.0

### ISSUE THREAD

**Issue by Dragonshadows** [Khroki/MCEdit-Unified#717]
Dunno what did i do but i can't open schematics anymore. Same result when using double click in folder or using prog to open. Worked fine earlier. Using win10 64bit and mcedit is also 64. My quess is that the file type association is wrong, dunno how, and i tried associate schematics to mcedit but no avail. I get same error. Deleted mcedit and dl new, no help. Can't use newest as it doesn't work. I get lots of errors with it. Searching net didn't offer help :( 
![mc-error1](https://cloud.githubusercontent.com/assets/21693677/18182413/9df06f02-7098-11e6-882c-0fa26d26ca12.jpg)

edit, i can add/import schematics to a existing world on mcedit 2.0.0. beta3 but it wont open them without world, i get this and bunch of others just opening program

An error occurred while opening C:/Users/Gekko/Documents/MCEdit/Schematics/16x16-modern-house.schematic 'SchematicFileAdapter' object has no attribute 'requireRevisions'
Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 207, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 284, in requireRevisions (self is a WorldEditor)
AttributeError: 'SchematicFileAdapter' object has no attribute 'requireRevisions'

**Comment by Dragonshadows** [comment]
update, schematics works fine on 1.5.3.0 but not on the 1.5.4.0, i still get the same error even i removed all mcedit from registry, and from comodo and avast

**Comment by Podshot** [comment]
Can you give us a download to this schematic file?

**Comment by Dragonshadows** [comment]
it's all schematic files, doesn't matter if it is made or dl from net, same result

**Comment by LaChal** [comment]
One of the internal feature added since 1.5.3.0 has broken the ability to open schematics like worlds.
You can still import them in an existing world.
